version: 2.1

jobs:

  ready:
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: update chrome
          command: |
            sudo apt-get install lsb-release
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  format:
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn format:list

  test:
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

  build:
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    docker:
      - image: circleci/node:10.15-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run: yarn publish

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - ready
      - lint:
          requires:
            - ready
      - format:
          requires:
            - ready
      - test:
          requires:
            - ready
      - build:
          requires:
            - ready
      - publish:
          requires:
            - lint
            - format
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
